<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="estiloimagenes.css">
    <title>F</title>
</head>
<body>
    <h1>Bienvenida :p</h1>
    <nav>
        <ul>
            <li>
                <a href="">No Olvidar</a>
            </li>
            <li>
                <a href="">TikTok</a>
            </li>
            <li>
                <a href="">Valorant</a>
            </li>
            <li>
                <a href="bad-bunny.html">Bad Bunny</a>
            </li>
            <li>
                <a href="index.html">Volver</a>
            </li>
        </ul>
    </nav>
    <div class="contenido">
        <h1>Galería de Fotos</h1>
        <div class="galeria">
            <div class="foto">
                <img src="img/PrimeraMuerte.jpg" alt="">
                <p>Primera Muerte con la Spectre, pium pium</p>
            </div>
        </div>
        <div class="galeria">
            <div class="foto">
                <img src="img/Junta14A.jpg" alt="">
                <p>Pisaste Línea para juntarnos el 14 de Abril de 2022 :p</p>
            </div>
        </div>
        <div class="galeria">
            <div class="foto">
                <img src="img/Girasol.jpg" alt="">
                <p>Este Girasol lo puse porque me recordo a tí</p>
            </div>
        </div>
        <div class="galeria">
            <div class="foto">
                <img src="img/Dibujo1Draw.jpg" alt="">
                <p>Dibujo de Draw uwu</p>
            </div>
        </div>
        <div class="galeria">
            <div class="foto">
                <img src="img/Dibujo2Draw.jpg" alt="">
                <p>Dibujo de Draw Denuevo jeje</p>
            </div>
        </div>
        <div class="galeria">
            <div class="foto">
                <img src="img/ojo.jpg" alt="">
                <p>Ojo Lindo</p>
            </div>
        </div>
        <div class="galeria">
            <div class="foto">
                <a href="">
                    <img src="img/TerapiOcupacional.jpg" alt="" >
                </a>
                <p>Mi rata x.x</p>
            </div>
        </div>
    </div>

    <footer>
        <p></p>
    </footer>

</body>

</html>